# For local development
version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-local
    environment:
      POSTGRES_DB: intern3_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: local_dev
      SRH_CONNECTION_STRING: "redis://redis:6379"

volumes:
  postgres_data:
  redis_data:
